services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: hft_clickhouse
    ports:
      - "8123:8123" 
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=hft123    # <-- فقط این خط باید بماند
    networks:
      - hft-net

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    #image: grafana/grafana-oss:latest
    image: grafana/grafana:latest
    container_name: hft_grafana
    ports:
      - "3000:3000"
    environment:
      #- GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=500ms
      - GF_DASHBOARDS_AUTO_REFRESH_INTERVALS=500ms,1s,2s,5s,10s,30s
      #- GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      #- GF_PLUGINS_ALLOW_UNSIGNED_PLUGINS=grafana-clickhouse-datasource
      
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana-plugins:/var/lib/grafana/plugins
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - hft-net

  java-app:
    build:
      context: ./java-app
      dockerfile: Dockerfile
    container_name: hft_java_producer
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - hft-net

networks:
  hft-net:
    driver: bridge